### ISSUE TITLE
Roadmap toward v1.0

### ISSUE THREAD

**Issue by gottacatchenall** [gottacatchenall/EcoDynamics.jl#3]
### Features
- [x] `Environment` types and generation via NL.jl integration 
- [x] Growth rates in response to environment

### Enhancements
- [x] Better default parameters for existing models 
- [x] Better printing via Term.jl

### Features
- [ ] `Trait` type that describes an arbitrary trait for particular species across space/time 
- [ ] Growth rates proportional to traits in response to environment 

### Features 
- [ ] Selection on `Trait`s in response to both environment and local community composition

## v0.??
- speciation based on clustering traits

**Comment by gottacatchenall** [comment]
it was much closer to a roadmap toward v0.2. rip
